### ISSUE TITLE
PyPI sdist is broken

### ISSUE THREAD

**Issue by chrisburr** [ozars/cymove#1]
When making a conda-forge package for this I noticed the source distribution on PyPI is broken as it is missing the `pyd` file.

```bash
$ wget https://pypi.io/packages/source/c/cymove/cymove-1.0.1.tar.gz
$ tar xvf cymove-1.0.1.tar.gz
x cymove-1.0.1/
x cymove-1.0.1/PKG-INFO
x cymove-1.0.1/README.md
x cymove-1.0.1/cymove/
x cymove-1.0.1/cymove/__init__.py
x cymove-1.0.1/cymove.egg-info/
x cymove-1.0.1/cymove.egg-info/PKG-INFO
x cymove-1.0.1/cymove.egg-info/SOURCES.txt
x cymove-1.0.1/cymove.egg-info/dependency_links.txt
x cymove-1.0.1/cymove.egg-info/not-zip-safe
x cymove-1.0.1/cymove.egg-info/top_level.txt
x cymove-1.0.1/setup.cfg
x cymove-1.0.1/setup.py
```

I think you just need to add a `MANIFEST.in` file containing `cymove/__init__.pxd`. It should also include the `LICENCE` file so the sdist complies with the MIT licence.

**Comment by ozars** [comment]
Hi @chrisburr. Sorry for noticing this issue so late. I missed this somehow.

It should be fixed now with new release. Also I deprecated this package since this feature got merged to Cython and available starting with v0.29.17 (`from libcpp.utility cimport move`). Please feel free to reopen this issue if it's not fixed.
